apiVersion: 1
datasources:
  - name: InfluxDB
    uid: influxdb-k6
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: ${INFLUX_DB}
    user: ${INFLUX_USERNAME}
    isDefault: true
    editable: false
    jsonData:
      version: InfluxQL
      httpMode: POST
      dbName: ${INFLUX_DB}
    secureJsonData:
      password: ${INFLUX_PASSWORD}
